/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ugarden;
import javax.swing.*;
/**
 *
 * @author hp431
 */
public class AnggrekGUI extends javax.swing.JFrame {

    /**
     * Creates new form AnggrekGUI
     */
    private Anggrek anggrek;
    private String namaTanaman;
    
    public AnggrekGUI() {
        initComponents();
        anggrek = new Anggrek();
        namaTanaman = JOptionPane.showInputDialog(null, "Beri Nama Tanaman");
        anggrek.setNamaTanaman(namaTanaman);
        labelNama.setText(namaTanaman);
        
        textStatusSiram.setText(String.valueOf(anggrek.getStatusPenyiraman()));
        textStatusPupuk.setText(String.valueOf(anggrek.getStatusPemupukan()));
        textSisaPupuk.setText(String.valueOf(anggrek.getJumlahPupuk()));
        textSisaAir.setText(String.valueOf(anggrek.getJumlahAir()));
        labelStatusPertumbuhan.setText(anggrek.getStatusTumbuh());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImage = new javax.swing.JLabel();
        buttonTambahAir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textSisaAir = new javax.swing.JTextField();
        textSisaPupuk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textStatusSiram = new javax.swing.JTextField();
        textStatusPupuk = new javax.swing.JTextField();
        labelStatusPertumbuhan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonTambahPupuk = new javax.swing.JButton();
        buttonSiram = new javax.swing.JButton();
        buttonBeriPupuk = new javax.swing.JButton();
        labelNama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menanam Anggrek");
        setLocationByPlatform(true);
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/benih.jpg"))); // NOI18N

        buttonTambahAir.setText("Tambah Air");
        buttonTambahAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahAirActionPerformed(evt);
            }
        });

        jLabel1.setText("Status Pertumbuhan :");

        textSisaAir.setEditable(false);
        textSisaAir.setText("0");
        textSisaAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSisaAirActionPerformed(evt);
            }
        });

        textSisaPupuk.setEditable(false);
        textSisaPupuk.setText("0");

        jLabel2.setText("Status Siram              : ");

        jLabel3.setText("Status Pupuk             :");

        textStatusSiram.setEditable(false);
        textStatusSiram.setText("0");

        textStatusPupuk.setEditable(false);
        textStatusPupuk.setText("0");

        labelStatusPertumbuhan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelStatusPertumbuhan.setText("Benih");

        jLabel5.setText("Sisa Air");

        jLabel6.setText("Sisa Pupuk");

        buttonTambahPupuk.setText("Tambah Pupuk");
        buttonTambahPupuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahPupukActionPerformed(evt);
            }
        });

        buttonSiram.setText("Siram");
        buttonSiram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiramActionPerformed(evt);
            }
        });

        buttonBeriPupuk.setText("Beri Pupuk");
        buttonBeriPupuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBeriPupukActionPerformed(evt);
            }
        });

        labelNama.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(textSisaAir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonTambahAir))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textSisaPupuk, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonTambahPupuk))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(labelStatusPertumbuhan)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textStatusPupuk)
                                            .addComponent(textStatusSiram, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelImage))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(buttonSiram, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonBeriPupuk, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelNama)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImage)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textStatusSiram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textStatusPupuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelStatusPertumbuhan)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSisaAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSisaPupuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambahAir)
                    .addComponent(buttonTambahPupuk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSiram, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBeriPupuk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String getResourceGambar()
    {
        String result = "";
        switch(anggrek.getStatusTumbuhInteger())
        {
            case 0:
                result = "/img/benih.jpg";
            break;
            case 1:
                result = "/img/tunas.jpg";
            break;
            case 2:
                result = "/img/kecil.jpg";
            break;
            case 3:
                result = "/img/besar.jpg";
            break;
            case 4:
                result = "/img/bunga.jpg";
            break;
            default :
                result = "/img/bunga.jpg";
            break;
        }
        return result;
    }
    private void refreshStatusPertumbuhan()
    {
        if(anggrek.isTumbuh())
        {
            anggrek.bertumbuh();
            JOptionPane.showMessageDialog(null, "Selamat, tanaman anda bertambah besar");
            labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(getResourceGambar())));// ubah image
            labelStatusPertumbuhan.setText(anggrek.getStatusTumbuh());
        }
    }
    
    private void buttonTambahAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahAirActionPerformed
        // TODO add your handling code here:
        anggrek.tambahAir();
        textSisaAir.setText(String.valueOf(anggrek.getJumlahAir()));
    }//GEN-LAST:event_buttonTambahAirActionPerformed

    private void textSisaAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSisaAirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSisaAirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void buttonSiramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiramActionPerformed
        // TODO add your handling code here:
        if(anggrek.getJumlahAir()<1)
        {
            JOptionPane.showMessageDialog(null, "Air Habis, tambahkan air dulu!");
        }
        else
        {
            anggrek.siramAir();
            refreshStatusPertumbuhan();
            textSisaAir.setText(String.valueOf(anggrek.getJumlahAir()));
            textStatusSiram.setText(String.valueOf(anggrek.getStatusPenyiraman()));
        }
    }//GEN-LAST:event_buttonSiramActionPerformed

    private void buttonBeriPupukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBeriPupukActionPerformed
        // TODO add your handling code here:
        if(anggrek.getJumlahPupuk()<1)
        {
            JOptionPane.showMessageDialog(null, "Pupuk Habis, tambahkan pupuk dulu!");
        }
        else
        {
            anggrek.beriPupuk();
            refreshStatusPertumbuhan();
            textSisaPupuk.setText(String.valueOf(anggrek.getJumlahPupuk()));
            textStatusPupuk.setText(String.valueOf(anggrek.getStatusPemupukan()));
        }
    }//GEN-LAST:event_buttonBeriPupukActionPerformed

    private void buttonTambahPupukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahPupukActionPerformed
        // TODO add your handling code here:
        anggrek.tambahPupuk();
        textSisaPupuk.setText(String.valueOf(anggrek.getJumlahPupuk()));
    }//GEN-LAST:event_buttonTambahPupukActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnggrekGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnggrekGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnggrekGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnggrekGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnggrekGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBeriPupuk;
    private javax.swing.JButton buttonSiram;
    private javax.swing.JButton buttonTambahAir;
    private javax.swing.JButton buttonTambahPupuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelStatusPertumbuhan;
    private javax.swing.JTextField textSisaAir;
    private javax.swing.JTextField textSisaPupuk;
    private javax.swing.JTextField textStatusPupuk;
    private javax.swing.JTextField textStatusSiram;
    // End of variables declaration//GEN-END:variables
}
